/**
 * 
 */
package multicados.internal.context;

import java.lang.reflect.Field;
import java.util.List;

import multicados.internal.domain.DomainResource;

/**
 * @author Ngoc Huy
 *
 */
public class MetadataProviderImpl<D extends DomainResource> implements SpecificLogicScopingMetadata<D> {

	private final List<Field> scopedAttributeNames;
	private final boolean isIdentifierAutoGenerated;

	public MetadataProviderImpl(List<Field> scopedAttributeNames, boolean isIdentifierAutoGenerated) {
		this.scopedAttributeNames = scopedAttributeNames;
		this.isIdentifierAutoGenerated = isIdentifierAutoGenerated;
	}

	@Override
	public List<Field> getScopedAttributeNames() {
		return scopedAttributeNames;
	}

	@Override
	public boolean isIdentifierAutoGenerated() {
		return isIdentifierAutoGenerated;
	}

}
