/**
 *
 */
package multicados.internal.service.crud;

import java.io.Serializable;
import java.util.List;
import java.util.Optional;

import javax.persistence.EntityExistsException;
import javax.persistence.EntityNotFoundException;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.PersistenceException;

import org.hibernate.Session;
import org.hibernate.SharedSessionContract;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import multicados.internal.context.ContextBuilder;
import multicados.internal.domain.DomainResource;
import multicados.internal.domain.DomainResourceContext;
import multicados.internal.domain.IdentifiableResource;
import multicados.internal.domain.builder.DomainResourceBuilder;
import multicados.internal.domain.builder.DomainResourceBuilderFactory;
import multicados.internal.domain.metadata.IdentifiableResourceMetadata;
import multicados.internal.domain.repository.GenericRepository;
import multicados.internal.domain.validation.DomainResourceValidator;
import multicados.internal.domain.validation.DomainResourceValidatorFactory;
import multicados.internal.domain.validation.Validation;
import multicados.internal.helper.Common;
import multicados.internal.helper.HibernateHelper;
import multicados.internal.service.ServiceResult;
import multicados.internal.service.crud.event.ServiceEventListenerGroups;

/**
 * @author Ngoc Huy
 *
 */
public abstract class AbstractGenericHibernateCUDService<TUPLE> extends ContextBuilder.AbstractContextBuilder
		implements GenericCRUDService<TUPLE, Session> {

	private static final Logger logger = LoggerFactory.getLogger(AbstractGenericHibernateCUDService.class);

	private final GenericRepository genericRepository;
	private final DomainResourceBuilderFactory builderFactory;
	private final DomainResourceValidatorFactory validatorFactory;
	private final DomainResourceContext resourceContext;

	private final ServiceEventListenerGroups eventListenerGroups;

	// @formatter:off
	protected AbstractGenericHibernateCUDService(
			DomainResourceContext resourceContext,
			DomainResourceBuilderFactory builderFactory,
			DomainResourceValidatorFactory validatorFactory,
			GenericRepository genericRepository)
			throws Exception {
		// @formatter:on
		this.resourceContext = resourceContext;
		this.builderFactory = builderFactory;
		this.validatorFactory = validatorFactory;
		eventListenerGroups = new ServiceEventListenerGroups(resourceContext);
		this.genericRepository = genericRepository;
	}

	@Override
	public <S extends Serializable, T extends IdentifiableResource<S>> ServiceResult create(Class<T> type,
			Serializable id, T model, Session session, boolean flushOnFinish) {
		if (logger.isDebugEnabled()) {
			logger.debug(String.format("Creating a resource of type %s with identifier %s", type.getName(), id));
		}

		try {
			// we want this process to be fail-fast
			checkIdentity(model.getId(), model, session);

			final DomainResourceBuilder<T> resourceBuilder = builderFactory.getBuilder(type);

			resourceBuilder.buildInsertion(model, session);

			final DomainResourceValidator<T> validator = validatorFactory.getValidator(type);
			final Validation validation = validator.isSatisfiedBy(session, id, model);

			if (!validation.isOk()) {
				return ServiceResult.bad(validation);
			}

			session.save(model);
			eventListenerGroups.firePostPersist(type, model);

			return ServiceResult.success(session, flushOnFinish);
		} catch (PersistenceException any) {
			// if the exception is indirectly PersistenceException, wrap it in
			// a PersistenceException so that we handle it in via ExceptionAdvisor
			return ServiceResult.failed(new PersistenceException(any));
		} catch (Exception any) {
			return ServiceResult.failed(any);
		}
	}

	/**
	 * Do an existence check for any non-auto-generated-identifier
	 * {@link DomainResource}.
	 * <p>
	 * Notice: This check may also pass in case the {@link Inheritance} applied to
	 * the resource is {@link InheritanceType#JOINED}.
	 * </p>
	 * 
	 * @param type
	 * @param model
	 * @param session
	 * @throws Exception
	 */
	@SuppressWarnings("unchecked")
	private <T extends DomainResource> void checkIdentity(Serializable id, T model, SharedSessionContract session)
			throws Exception {
		final Class<IdentifiableResource<?>> resourceType = (Class<IdentifiableResource<?>>) model.getClass();
		// if this resource's id is auto-generated, we skip
		if (resourceContext.getMetadata(resourceType).unwrap(IdentifiableResourceMetadata.class)
				.isIdentifierAutoGenerated()) {
			return;
		}

		if (genericRepository.doesExist(resourceType, HibernateHelper.hasId(resourceType, id, session), session)) {
			throw new PersistenceException(new EntityExistsException(Common.existed(List.of(id.toString()))));
		}
	}

	@Override
	public <S extends Serializable, T extends IdentifiableResource<S>> ServiceResult update(Class<T> type,
			Serializable id, T model, Session session, boolean flushOnFinish) {
		if (logger.isDebugEnabled()) {
			logger.debug(String.format("Updating a resource of type %s with identifier %s", type.getName(), id));
		}

		try {
			final Serializable actualId = Optional.ofNullable(id).orElse(model.getId());
			final T persistence = session.find(type, actualId);

			if (persistence == null) {
				throw new PersistenceException(new EntityNotFoundException(
						actualId == null ? Common.notFound() : Common.notFound(List.of(actualId.toString()))));
			}

			final DomainResourceBuilder<T> resourceBuilder = builderFactory.getBuilder(type);

			resourceBuilder.buildUpdate(model, persistence, session);

			final DomainResourceValidator<T> validator = validatorFactory.getValidator(type);
			final Validation validation = validator.isSatisfiedBy(session, actualId, persistence);

			if (!validation.isOk()) {
				return ServiceResult.bad(validation);
			}

			session.merge(persistence);

			return ServiceResult.success(session, flushOnFinish);
		} catch (Exception any) {
			return ServiceResult.failed(any);
		}
	}

	@Override
	public void summary() {
		if (logger.isDebugEnabled()) {
			logger.debug(eventListenerGroups.toString());
		}
	}

}
